# Generated by Django 6.0.2 on 2026-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Temporary content'),
            preserve_default=False,
        ),
    ]
